##################################################################################
#                                                                                 
#   Config Rulesd Pack:                                                             
#     Best Practices for Serverless Data Protection                         
#                                                                               
#   This pack helps verify compliance for serverless services and data protection.   
#   Included servcices: Lambda, API Gateway, DyanmoDb, S3
#   
#   Additional other config rules can be found at: https://docs.aws.amazon.com/config/latest/developerguide/managed-rules-by-aws-config.html                                                                                 
#                                                                                 
##################################################################################

Parameters:
#API
  ApiGwEndpointTypeCheckParamEndpointConfigurationTypes:
    Default: REGIONAL, PRIVATE, EDGE
    Type: String
Resources:
#API
# api-gw-associated-with-waf
  ApiGwAssociatedWithWaf:
    Properties:
      ConfigRuleName: api-gw-associated-with-waf
      Scope:
        ComplianceResourceTypes:
        - AWS::ApiGateway::Stage
      Source:
        Owner: AWS
        SourceIdentifier: API_GW_ASSOCIATED_WITH_WAF
    Type: AWS::Config::ConfigRule
# api-gw-cache-enabled-and-encrypted
  ApiGwCacheEnabledAndEncrypted:
    Properties:
      ConfigRuleName: api-gw-cache-enabled-and-encrypted
      Scope:
        ComplianceResourceTypes:
        - AWS::ApiGateway::Stage
      Source:
        Owner: AWS
        SourceIdentifier: API_GW_CACHE_ENABLED_AND_ENCRYPTED
    Type: AWS::Config::ConfigRule
#api-gw-endpoint-type-check 
  ApiGwEndpointTypeCheck:
    Properties:
      ConfigRuleName: api-gw-endpoint-type-check
      InputParameters:
        endpointConfigurationTypes:
          Fn::If:
          - apiGwEndpointTypeCheckParamEndpointConfigurationTypes
          - Ref: ApiGwEndpointTypeCheckParamEndpointConfigurationTypes
          - Ref: AWS::NoValue
      Scope:
        ComplianceResourceTypes:
        - AWS::ApiGateway::RestApi
      Source:
        Owner: AWS
        SourceIdentifier: API_GW_ENDPOINT_TYPE_CHECK
    Type: AWS::Config::ConfigRule
#api-gw-execution-logging-enabled
  ApiGwExecutionLoggingEnabled:
    Properties:
      ConfigRuleName: api-gw-execution-logging-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::ApiGateway::Stage
        - AWS::ApiGatewayV2::Stage
      Source:
        Owner: AWS
        SourceIdentifier: API_GW_EXECUTION_LOGGING_ENABLED
    Type: AWS::Config::ConfigRule
#api-gw-ssl-enabled
  ApiGwSslEnabled:
    Properties:
      ConfigRuleName: api-gw-ssl-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::ApiGateway::Stage
      Source:
        Owner: AWS
        SourceIdentifier: API_GW_SSL_ENABLED
    Type: AWS::Config::ConfigRule
Conditions:
#API
  apiGwEndpointTypeCheckParamEndpointConfigurationTypes:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: ApiGwEndpointTypeCheckParamEndpointConfigurationTypes